spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ayan_prod
    username: ayan_prod_user
    password: ayan
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
